// Seed data for the mock backend (and the Supabase seed script).
//
// Reference date: 2026-05-06.
//
// Designed so the dashboard alerts fire end-to-end against the new
// flavors model:
//   - "Фруктоза"                       → low stock  (3.2 кг < min 5 кг)
//   - "Лимонная кислота"               → expiring on 2026-05-25 (19 days)
//   - "Ароматизатор «Лимон» (масло)"   → expiring on 2026-06-01 (26 days)
//   - "Ароматизатор «Грейпфрут» (масло)" → low stock (200 мл < min 250 мл)
//   - "Ароматизатор «Манго» (масло)"   → expiring on 2026-05-30 (24 days)

export const seedData = {
  // ── ingredients ───────────────────────────────────────────────────
  ingredients: [
    {
      id: 'ing-001',
      name_ru: 'Декстроза (глюкоза)',
      unit: 'кг',
      current_stock: 8.5,
      min_threshold: 5,
      lot_number: 'DX-2025-114',
      expiry_date: '2027-04-15',
      supplier: 'ООО «Сладкие компоненты»',
      notes: '',
      updated_at: '2026-04-20T09:00:00.000Z',
    },
    {
      id: 'ing-002',
      name_ru: 'Фруктоза',
      unit: 'кг',
      current_stock: 3.2,
      min_threshold: 5,
      lot_number: 'FR-2025-088',
      expiry_date: '2026-12-20',
      supplier: 'ООО «Сладкие компоненты»',
      notes: 'Заказан подвоз у поставщика',
      updated_at: '2026-05-04T14:30:00.000Z',
    },
    {
      id: 'ing-003',
      name_ru: 'Лимонная кислота безводная',
      unit: 'кг',
      current_stock: 12,
      min_threshold: 3,
      lot_number: 'CA-2024-201',
      expiry_date: '2026-05-25',
      supplier: 'ХимТрейд',
      notes: 'Использовать в первую очередь',
      updated_at: '2026-04-28T10:15:00.000Z',
    },
    {
      id: 'ing-004',
      name_ru: 'Аскорбиновая кислота (вит. C)',
      unit: 'г',
      current_stock: 620,
      min_threshold: 200,
      lot_number: 'VC-2025-042',
      expiry_date: '2026-11-10',
      supplier: 'ХимТрейд',
      notes: '',
      updated_at: '2026-04-12T08:00:00.000Z',
    },
    {
      id: 'ing-005',
      name_ru: 'Цитрат натрия',
      unit: 'кг',
      current_stock: 2.8,
      min_threshold: 1,
      lot_number: 'SC-2025-019',
      expiry_date: '2027-08-01',
      supplier: 'ХимТрейд',
      notes: '',
      updated_at: '2026-03-30T11:00:00.000Z',
    },
    {
      id: 'ing-006',
      name_ru: 'Хлорид калия',
      unit: 'кг',
      current_stock: 2.1,
      min_threshold: 0.5,
      lot_number: 'KCl-2025-007',
      expiry_date: '2027-03-15',
      supplier: 'ХимТрейд',
      notes: '',
      updated_at: '2026-04-05T09:30:00.000Z',
    },
    {
      id: 'ing-007',
      name_ru: 'Хлорид магния',
      unit: 'кг',
      current_stock: 1.4,
      min_threshold: 0.5,
      lot_number: 'MgCl-2025-011',
      expiry_date: '2027-02-20',
      supplier: 'ХимТрейд',
      notes: '',
      updated_at: '2026-04-05T09:35:00.000Z',
    },
    {
      id: 'ing-008',
      name_ru: 'Витаминный премикс B-комплекс',
      unit: 'г',
      current_stock: 240,
      min_threshold: 100,
      lot_number: 'PMX-2025-003',
      expiry_date: '2026-08-15',
      supplier: 'Нутрилайн',
      notes: 'Хранить при +5…+10 °C',
      updated_at: '2026-04-18T13:00:00.000Z',
    },
    {
      id: 'ing-009',
      name_ru: 'Ароматизатор «Цитрус» (порошок)',
      unit: 'г',
      current_stock: 750,
      min_threshold: 300,
      lot_number: 'AR-CT-2025-022',
      expiry_date: '2026-09-30',
      supplier: 'Аромасинтез',
      notes: 'Универсальная цитрусовая основа',
      updated_at: '2026-04-22T16:45:00.000Z',
    },
    {
      id: 'ing-010',
      name_ru: 'Винная кислота',
      unit: 'кг',
      current_stock: 1.8,
      min_threshold: 0.5,
      lot_number: 'TA-2025-014',
      expiry_date: '2026-12-31',
      supplier: 'ХимТрейд',
      notes: '',
      updated_at: '2026-04-02T10:00:00.000Z',
    },
    {
      id: 'ing-011',
      name_ru: 'Глицерин пищевой',
      unit: 'л',
      current_stock: 5.6,
      min_threshold: 2,
      lot_number: 'GLY-2025-031',
      expiry_date: '2027-06-10',
      supplier: 'Аромасинтез',
      notes: '',
      updated_at: '2026-04-15T12:00:00.000Z',
    },
    {
      id: 'ing-012',
      name_ru: 'Лецитин подсолнечный (раствор)',
      unit: 'л',
      current_stock: 2.4,
      min_threshold: 1,
      lot_number: 'LEC-2025-009',
      expiry_date: '2026-10-20',
      supplier: 'Аромасинтез',
      notes: '',
      updated_at: '2026-04-10T15:00:00.000Z',
    },
    {
      id: 'ing-013',
      name_ru: 'Ароматизатор «Лимон» (масло)',
      unit: 'мл',
      current_stock: 480,
      min_threshold: 150,
      lot_number: 'AR-LM-2025-018',
      expiry_date: '2026-06-01',
      supplier: 'Аромасинтез',
      notes: 'Хранить в темноте',
      updated_at: '2026-04-25T11:20:00.000Z',
    },
    {
      id: 'ing-014',
      name_ru: 'Концентрат лимонного сока',
      unit: 'л',
      current_stock: 3.5,
      min_threshold: 1,
      lot_number: 'LJ-2025-027',
      expiry_date: '2026-07-25',
      supplier: 'Соки-Юг',
      notes: 'Хранить при +2…+8 °C',
      updated_at: '2026-04-26T09:00:00.000Z',
    },
    // ── New flavor extracts (Phase 3) ─────────────────────────────
    {
      id: 'ing-015',
      name_ru: 'Ароматизатор «Апельсин» (масло)',
      unit: 'мл',
      current_stock: 520,
      min_threshold: 150,
      lot_number: 'AR-OR-2025-031',
      expiry_date: '2026-08-12',
      supplier: 'Аромасинтез',
      notes: 'Хранить в темноте',
      updated_at: '2026-04-25T11:25:00.000Z',
    },
    {
      id: 'ing-016',
      name_ru: 'Ароматизатор «Грейпфрут» (масло)',
      unit: 'мл',
      current_stock: 200,
      min_threshold: 250,
      lot_number: 'AR-GR-2025-029',
      expiry_date: '2026-09-05',
      supplier: 'Аромасинтез',
      notes: 'Заказан подвоз у поставщика',
      updated_at: '2026-05-03T15:10:00.000Z',
    },
    {
      id: 'ing-017',
      name_ru: 'Ароматизатор «Манго» (масло)',
      unit: 'мл',
      current_stock: 380,
      min_threshold: 150,
      lot_number: 'AR-MN-2025-022',
      expiry_date: '2026-05-30',
      supplier: 'Аромасинтез',
      notes: 'Срок годности подходит к концу',
      updated_at: '2026-04-29T10:40:00.000Z',
    },
  ],

  // ── flavors ───────────────────────────────────────────────────────
  flavors: [
    {
      id: 'lemon',
      name_ru: 'Лимон',
      color_hex: '#FFD700',
      active: true,
      notes: '',
    },
    {
      id: 'orange',
      name_ru: 'Апельсин',
      color_hex: '#FFA500',
      active: true,
      notes: '',
    },
    {
      id: 'grapefruit',
      name_ru: 'Грейпфрут',
      color_hex: '#FF6B6B',
      active: true,
      notes: '',
    },
    {
      id: 'mango',
      name_ru: 'Манго',
      color_hex: '#FFB347',
      active: true,
      notes: '',
    },
  ],

  // ── concentrate types ─────────────────────────────────────────────
  concentrate_types: [
    {
      id: 'concentrate_a',
      name_ru: 'Концентрат A',
      output_unit: 'шт',
      output_quantity: 1,
      is_flavor_specific: true,
      base_composition: [
        { ingredient_id: 'ing-001', amount: 800, unit: 'г' },
        { ingredient_id: 'ing-002', amount: 400, unit: 'г' },
        { ingredient_id: 'ing-003', amount: 60, unit: 'г' },
        { ingredient_id: 'ing-004', amount: 30, unit: 'г' },
        { ingredient_id: 'ing-005', amount: 50, unit: 'г' },
        { ingredient_id: 'ing-006', amount: 20, unit: 'г' },
        { ingredient_id: 'ing-007', amount: 15, unit: 'г' },
        { ingredient_id: 'ing-008', amount: 8, unit: 'г' },
      ],
      protocol_steps: [
        'Подготовить чистую пластиковую коробку и перчатки',
        'Взвесить все сухие ингредиенты согласно рецепту',
        'Высыпать в коробку: соли → кислоты → сахара → витамины',
        'Тщательно перемешать сухим венчиком 3 минуты',
        'Закрыть коробку, наклеить этикетку с номером партии и датой',
      ],
      notes: '',
    },
    {
      id: 'concentrate_b',
      name_ru: 'Концентрат B',
      output_unit: 'шт',
      output_quantity: 1,
      is_flavor_specific: false,
      base_composition: [
        { ingredient_id: 'ing-003', amount: 200, unit: 'г' },
        { ingredient_id: 'ing-010', amount: 100, unit: 'г' },
      ],
      protocol_steps: [
        'Взвесить лимонную кислоту',
        'Взвесить винную кислоту',
        'Смешать в малой пластиковой коробке',
        'Закрыть, наклеить этикетку с номером партии и датой',
      ],
      notes: 'Общий рецепт для всех вкусов',
    },
    {
      id: 'emulsion',
      name_ru: 'Жидкая эмульсия',
      output_unit: 'л',
      output_quantity: 10,
      is_flavor_specific: true,
      base_composition: [
        { ingredient_id: 'ing-011', amount: 0.5, unit: 'л' },
        { ingredient_id: 'ing-012', amount: 0.3, unit: 'л' },
        { ingredient_id: 'ing-004', amount: 5, unit: 'г' },
      ],
      protocol_steps: [
        'Подготовить гомогенизатор и стерильную тару',
        'Налить деионизированную воду до отметки',
        'Добавить глицерин и лецитин',
        'Запустить гомогенизатор на 5 минут',
        'Перелить в стерильную тару, наклеить этикетку',
      ],
      notes: '',
    },
  ],

  // ── recipe variants ──────────────────────────────────────────────
  // 4 for concentrate_a, 4 for emulsion, 0 for concentrate_b.
  // Demonstrates each override op:
  //   - lemon / orange     → just `add` the flavor extract
  //   - grapefruit         → `add` extract + `modify` an existing amount
  //   - mango              → `add` extract + `remove` an ingredient
  recipe_variants: [
    // Concentrate A × 4 ──────────────
    {
      id: 'concentrate_a__lemon',
      concentrate_type_id: 'concentrate_a',
      flavor_id: 'lemon',
      overrides: {
        add: [{ ingredient_id: 'ing-013', amount: 25, unit: 'мл' }],
        modify: [],
        remove: [],
      },
      protocol_addendum: [],
      notes: '',
    },
    {
      id: 'concentrate_a__orange',
      concentrate_type_id: 'concentrate_a',
      flavor_id: 'orange',
      overrides: {
        add: [{ ingredient_id: 'ing-015', amount: 25, unit: 'мл' }],
        modify: [],
        remove: [],
      },
      protocol_addendum: [],
      notes: '',
    },
    {
      id: 'concentrate_a__grapefruit',
      concentrate_type_id: 'concentrate_a',
      flavor_id: 'grapefruit',
      overrides: {
        add: [{ ingredient_id: 'ing-016', amount: 25, unit: 'мл' }],
        modify: [{ ingredient_id: 'ing-003', amount: 80, unit: 'г' }],
        remove: [],
      },
      protocol_addendum: ['После премешивания добавить грейпфрутовое масло шприц-дозатором'],
      notes: 'Усиленная кислотность под характерную горчинку',
    },
    {
      id: 'concentrate_a__mango',
      concentrate_type_id: 'concentrate_a',
      flavor_id: 'mango',
      overrides: {
        add: [{ ingredient_id: 'ing-017', amount: 30, unit: 'мл' }],
        modify: [],
        remove: ['ing-004'],
      },
      protocol_addendum: [],
      notes: 'Манго даёт натуральную витаминизацию — аскорбинка не нужна',
    },

    // Emulsion × 4 ──────────────
    {
      id: 'emulsion__lemon',
      concentrate_type_id: 'emulsion',
      flavor_id: 'lemon',
      overrides: {
        add: [
          { ingredient_id: 'ing-013', amount: 50, unit: 'мл' },
          { ingredient_id: 'ing-014', amount: 1.5, unit: 'л' },
        ],
        modify: [],
        remove: [],
      },
      protocol_addendum: ['Добавить ароматизатор и концентрат лимонного сока', 'Гомогенизировать ещё 3 минуты'],
      notes: '',
    },
    {
      id: 'emulsion__orange',
      concentrate_type_id: 'emulsion',
      flavor_id: 'orange',
      overrides: {
        add: [{ ingredient_id: 'ing-015', amount: 50, unit: 'мл' }],
        modify: [],
        remove: [],
      },
      protocol_addendum: ['Добавить апельсиновое масло и гомогенизировать ещё 3 минуты'],
      notes: '',
    },
    {
      id: 'emulsion__grapefruit',
      concentrate_type_id: 'emulsion',
      flavor_id: 'grapefruit',
      overrides: {
        add: [{ ingredient_id: 'ing-016', amount: 50, unit: 'мл' }],
        modify: [{ ingredient_id: 'ing-011', amount: 0.7, unit: 'л' }],
        remove: [],
      },
      protocol_addendum: ['Добавить грейпфрутовое масло и гомогенизировать ещё 3 минуты'],
      notes: 'Больше глицерина для смягчения горчинки',
    },
    {
      id: 'emulsion__mango',
      concentrate_type_id: 'emulsion',
      flavor_id: 'mango',
      overrides: {
        add: [{ ingredient_id: 'ing-017', amount: 60, unit: 'мл' }],
        modify: [],
        remove: ['ing-004'],
      },
      protocol_addendum: ['Добавить масло манго и гомогенизировать ещё 4 минуты на низких оборотах'],
      notes: 'Без аскорбинки — манго достаточно витаминизирует эмульсию',
    },
  ],

  // ── batches ──────────────────────────────────────────────────────
  // Historical batches in the new shape: each row reflects what would have
  // been used under the new (type, flavor) recipe model. ingredients_used
  // is denormalized so the journal stays readable even if recipes change.
  batches: [
    {
      batch_id: 'concentrate_a-lemon-20260505-01',
      concentrate_type_id: 'concentrate_a',
      concentrate_type_name_ru: 'Концентрат A',
      flavor_id: 'lemon',
      flavor_name_ru: 'Лимон',
      produced_at: '2026-05-05T11:30:00.000Z',
      produced_by: 'Иван Петров',
      quantity: 1,
      ingredients_used: [
        { ingredient_id: 'ing-001', name_ru: 'Декстроза (глюкоза)', amount: 800, unit: 'г', lot_number: 'DX-2025-114' },
        { ingredient_id: 'ing-002', name_ru: 'Фруктоза', amount: 400, unit: 'г', lot_number: 'FR-2025-088' },
        { ingredient_id: 'ing-003', name_ru: 'Лимонная кислота безводная', amount: 60, unit: 'г', lot_number: 'CA-2024-201' },
        { ingredient_id: 'ing-004', name_ru: 'Аскорбиновая кислота (вит. C)', amount: 30, unit: 'г', lot_number: 'VC-2025-042' },
        { ingredient_id: 'ing-005', name_ru: 'Цитрат натрия', amount: 50, unit: 'г', lot_number: 'SC-2025-019' },
        { ingredient_id: 'ing-006', name_ru: 'Хлорид калия', amount: 20, unit: 'г', lot_number: 'KCl-2025-007' },
        { ingredient_id: 'ing-007', name_ru: 'Хлорид магния', amount: 15, unit: 'г', lot_number: 'MgCl-2025-011' },
        { ingredient_id: 'ing-008', name_ru: 'Витаминный премикс B-комплекс', amount: 8, unit: 'г', lot_number: 'PMX-2025-003' },
        { ingredient_id: 'ing-013', name_ru: 'Ароматизатор «Лимон» (масло)', amount: 25, unit: 'мл', lot_number: 'AR-LM-2025-018' },
      ],
      notes: '',
      status: 'completed',
      shift_id: null,
    },
    {
      batch_id: 'emulsion-mango-20260504-01',
      concentrate_type_id: 'emulsion',
      concentrate_type_name_ru: 'Жидкая эмульсия',
      flavor_id: 'mango',
      flavor_name_ru: 'Манго',
      produced_at: '2026-05-04T15:00:00.000Z',
      produced_by: 'Иван Петров',
      quantity: 1,
      ingredients_used: [
        { ingredient_id: 'ing-011', name_ru: 'Глицерин пищевой', amount: 0.5, unit: 'л', lot_number: 'GLY-2025-031' },
        { ingredient_id: 'ing-012', name_ru: 'Лецитин подсолнечный (раствор)', amount: 0.3, unit: 'л', lot_number: 'LEC-2025-009' },
        { ingredient_id: 'ing-017', name_ru: 'Ароматизатор «Манго» (масло)', amount: 60, unit: 'мл', lot_number: 'AR-MN-2025-022' },
      ],
      notes: 'Гомогенизация на низких оборотах прошла без замечаний',
      status: 'completed',
      shift_id: null,
    },
    {
      batch_id: 'concentrate_b-20260502-01',
      concentrate_type_id: 'concentrate_b',
      concentrate_type_name_ru: 'Концентрат B',
      flavor_id: null,
      flavor_name_ru: null,
      produced_at: '2026-05-02T10:15:00.000Z',
      produced_by: 'Иван Петров',
      quantity: 1,
      ingredients_used: [
        { ingredient_id: 'ing-003', name_ru: 'Лимонная кислота безводная', amount: 200, unit: 'г', lot_number: 'CA-2024-201' },
        { ingredient_id: 'ing-010', name_ru: 'Винная кислота', amount: 100, unit: 'г', lot_number: 'TA-2025-014' },
      ],
      notes: '',
      status: 'completed',
      shift_id: null,
    },
    {
      batch_id: 'concentrate_a-orange-20260430-01',
      concentrate_type_id: 'concentrate_a',
      concentrate_type_name_ru: 'Концентрат A',
      flavor_id: 'orange',
      flavor_name_ru: 'Апельсин',
      produced_at: '2026-04-30T09:45:00.000Z',
      produced_by: 'Иван Петров',
      quantity: 2,
      ingredients_used: [
        { ingredient_id: 'ing-001', name_ru: 'Декстроза (глюкоза)', amount: 1600, unit: 'г', lot_number: 'DX-2025-114' },
        { ingredient_id: 'ing-002', name_ru: 'Фруктоза', amount: 800, unit: 'г', lot_number: 'FR-2025-088' },
        { ingredient_id: 'ing-003', name_ru: 'Лимонная кислота безводная', amount: 120, unit: 'г', lot_number: 'CA-2024-201' },
        { ingredient_id: 'ing-004', name_ru: 'Аскорбиновая кислота (вит. C)', amount: 60, unit: 'г', lot_number: 'VC-2025-042' },
        { ingredient_id: 'ing-005', name_ru: 'Цитрат натрия', amount: 100, unit: 'г', lot_number: 'SC-2025-019' },
        { ingredient_id: 'ing-006', name_ru: 'Хлорид калия', amount: 40, unit: 'г', lot_number: 'KCl-2025-007' },
        { ingredient_id: 'ing-007', name_ru: 'Хлорид магния', amount: 30, unit: 'г', lot_number: 'MgCl-2025-011' },
        { ingredient_id: 'ing-008', name_ru: 'Витаминный премикс B-комплекс', amount: 16, unit: 'г', lot_number: 'PMX-2025-003' },
        { ingredient_id: 'ing-015', name_ru: 'Ароматизатор «Апельсин» (масло)', amount: 50, unit: 'мл', lot_number: 'AR-OR-2025-031' },
      ],
      notes: 'Двойная партия для запаса',
      status: 'completed',
      shift_id: null,
    },
    {
      batch_id: 'emulsion-lemon-20260428-01',
      concentrate_type_id: 'emulsion',
      concentrate_type_name_ru: 'Жидкая эмульсия',
      flavor_id: 'lemon',
      flavor_name_ru: 'Лимон',
      produced_at: '2026-04-28T14:20:00.000Z',
      produced_by: 'Иван Петров',
      quantity: 1,
      ingredients_used: [
        { ingredient_id: 'ing-011', name_ru: 'Глицерин пищевой', amount: 0.5, unit: 'л', lot_number: 'GLY-2025-031' },
        { ingredient_id: 'ing-012', name_ru: 'Лецитин подсолнечный (раствор)', amount: 0.3, unit: 'л', lot_number: 'LEC-2025-009' },
        { ingredient_id: 'ing-004', name_ru: 'Аскорбиновая кислота (вит. C)', amount: 5, unit: 'г', lot_number: 'VC-2025-042' },
        { ingredient_id: 'ing-013', name_ru: 'Ароматизатор «Лимон» (масло)', amount: 50, unit: 'мл', lot_number: 'AR-LM-2025-018' },
        { ingredient_id: 'ing-014', name_ru: 'Концентрат лимонного сока', amount: 1.5, unit: 'л', lot_number: 'LJ-2025-027' },
      ],
      notes: '',
      status: 'completed',
      shift_id: null,
    },
  ],

  // ── settings (key/value rows in the live DB; flat-map shape here) ─
  settings: {
    expiry_warning_days: 30,
    operator_name: '',
  },
};
